from aiogram.dispatcher.filters.state import State, StatesGroup
class Partner(StatesGroup):
    name = State()
    lastname = State()
    phone = State()
    tg = State()
    email = State()
    id = State()
    marketName = State()
    marketId = State()
    marketCall = State()
    licenceID = State()
    address = State()
    demand = State()
    confirm = State()
    category = State()
    marketpic1 = State()
    marketpic2 = State()
    humo = State()
    uzcard = State()
    region = State()
    city = State()
